### ISSUE TITLE
does nothing

### ISSUE THREAD

**Issue by ppsnipes** [vanflux/jstetris-bot#1]
set it all up properly and the bot menu does pop up but it literally just doesn't do anything.

**Comment by vanflux** [comment]
I downloaded the bot now in firefox and chrome and it works in both perfectly.
Explain better what happened, what you expect?

**Comment by ppsnipes** [comment]
i'm on opera GX

**Comment by ppsnipes** [comment]
i tried it on chrome and it still does nothing .-.
https://gyazo.com/4243fe7d112297965079f6b2938f3f8c

**Comment by vanflux** [comment]
> 

What is your chrome version?
Could you start a game, run the bot(that doesn't work), open the console with F12 and take a screenshot of the console logs?

**Comment by eYuM-coder** [comment]
> > 
> 
> What is your chrome version? Could you start a game, run the bot(that doesn't work), open the console with F12 and take a screenshot of the console logs?

If ur wondering what the error is, here you go.

![image](https://user-images.githubusercontent.com/101909226/206596798-718a0ea5-812b-42c6-a9df-599e1738c415.png)

**Comment by eYuM-coder** [comment]
Ok, I found the root cause of the error, Chrome has updated. Meaning that the bot is now deprecated and WON'T work anymore.

**Comment by vanflux** [comment]
> Ok, I found the root cause of the error, Chrome has updated. Meaning that the bot is now deprecated and WON'T work anymore.

I'm using chrome 108.0.5359.124(latest) and its working. I wasn't able to replicate the issue.

![image](https://user-images.githubusercontent.com/16052531/211643516-b036a2a5-a6d3-4320-b662-39875269a9c7.png)

**Comment by vanflux** [comment]
OMG I FINALLY FOUND THE REAL PROBLEM!!!

THE SKINS USE IMAGES!!!

For now, try to use the vanilla skin, solid color blocks... The game renders custom skin blocks with images, maybe some game functions need to be patched to it works... Thanks for the log @Boeing-737-800

**Comment by eYuM-coder** [comment]
> OMG I FINALLY FOUND THE REAL PROBLEM!!!
> 
> THE SKINS USE IMAGES!!!
> 
> For now, try to use the vanilla skin, solid color blocks... The game renders custom skin blocks with images, maybe some game functions need to be patched to it works... Thanks for the log @Boeing-737-800

No worries! I'm out for catching any errors with pretty much anything

**Comment by eYuM-coder** [comment]
![image](https://user-images.githubusercontent.com/101909226/216438802-79b5b13e-22a5-4335-80d4-186d6a47ac98.png)
Also noticed this error, standard jstris with its redirects XD
